version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: rtfd-mlops-zookeeper-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: fraud
    ports:
      - "5432:5432"
    volumes:
      - ./infra/pgdata:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: rtfd-mlops-kafka-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"      # host <-> EXTERNAL
      - "29092:29092"    # host <-> INTERNAL (handy for testing)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Bind two listeners:
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      # Advertise different addresses to containers vs host:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://rtfd-mlops-kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
